name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x
        cache: true
        cache-dependency-path: '**/*.csproj'
    - name: Restore
      run: dotnet restore
    - name: Restore certificate
      env:
        LAMPARRAY_CERT: ${{ secrets.LAMPARRAY_CERT }}
      run: |
        if ($env:LAMPARRAY_CERT) {
          [IO.File]::WriteAllBytes("LenovoLegionToolkit.LampArray.cer", [Convert]::FromBase64String($env:LAMPARRAY_CERT))
        }
      shell: powershell

    - name: Build
      run: .\make_action.bat
    - name: Verify installer
      run: |
        $installerPath = "build_installer\LenovoLegionToolkitSetup.exe"
        if (-not (Test-Path $installerPath)) {
          Write-Error "Installer file not found at $installerPath"
          exit 1
        }
      shell: powershell
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: installer
        path: build_installer\LenovoLegionToolkitSetup.exe
